# Generated by Django 3.1.5 on 2021-01-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_product_img_src'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.BigIntegerField(default=0),
        ),
    ]
