# Generated by Django 3.1.5 on 2021-01-24 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_cartitem_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='items',
        ),
    ]
