# Generated by Django 3.1.5 on 2021-02-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20210202_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='items',
            field=models.ManyToManyField(related_name='_shoppingcart_items_+', to='main.Item'),
        ),
    ]
