# Generated by Django 3.1.5 on 2021-02-02 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_shoppingcart_items'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
